version: '3.8'
services:
  usuario:
    build:
      context: ../usuario
    ports:
      - "8081:8080"
    volumes:
      - ../usuario/wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=usuario
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@fullstackusuario_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend

  ordenes:
    build:
      context: ../Ordenes
    ports:
      - "8083:8080"
    volumes:
      - ../Ordenes/wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=orders
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@dbcloudmdy1101_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMINF
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend
  
  pricing:
    build:
      context: ../Pricing
    ports:
      - "8084:8080"
    volumes:
      - ../Pricing/wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=Pricing
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@XXXX?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend
    
  pagos:
    build:
      context: ../Pagos
    ports:
      - "8085:8080"
    volumes:
      - ../Pagos/wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=Pagos
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@basefullstack_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=USUARIO_FULLSTACK
      - SPRING_DATASOURCE_PASSWORD=RenatayGaspar$2019
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend
  
  notificaciones:
    build:
      context: ../Notificaciones
    ports:
      - "8086:8080"
    volumes:
      - ../Notificaciones/wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=Notificaciones
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@notificaciones_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend

  # inventario:
  #   build:
  #     context: ../Inventario
  #   ports:
  #     - "8087:8080"
  #   volumes:
  #     - ../Inventario/wallet:/app/wallet
  #   environment:
  #     - SPRING_APPLICATION_NAME=Inventario
  #     - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@microservinventary_high?TNS_ADMIN=/app/wallet
  #     - SPRING_DATASOURCE_USERNAME=ADMIN
  #     - SPRING_DATASOURCE_PASSWORD=Inventario202506
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #     - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
  #   networks:
  #     - backend

  # productos:
  #   build:
  #     context: ../Productos
  #   ports:
  #     - "8088:8080"
  #   volumes:
  #     - ../Productos/wallet:/app/wallet
  #   environment:
  #     - SPRING_APPLICATION_NAME=productos
  #     - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@kgrasril5bsgzi0i_high?TNS_ADMIN=/app/wallet
  #     - SPRING_DATASOURCE_USERNAME=ADMIN
  #     - SPRING_DATASOURCE_PASSWORD=FullStack-001
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #     - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge